### ISSUE TITLE
Doesn't work with Sidekiq 4.2+: undefined method `register' for Sidekiq::WebApplication:Class

### ISSUE THREAD

**Issue by baburdick** [kosmatov/sidekiq-benchmark#17]
Updating Sidekiq to v4.2.2 prevents sidekiq-benchmark from loading. This error message is displayed:
```
Bundler::GemRequireError: There was an error while trying to load the gem 'sidekiq-benchmark'.
Gem Load Error is: undefined method `register' for Sidekiq::WebApplication:Class
Backtrace for gem load error is:
~/.rvm/gems/ruby-2.2.4@my_service/gems/sidekiq-benchmark-0.4.1/lib/sidekiq-benchmark/web.rb:12:in `registered'
~/.rvm/gems/ruby-2.2.4@my_service/gems/sidekiq-4.2.2/lib/sidekiq/web.rb:101:in `register'
~/.rvm/gems/ruby-2.2.4@my_service/gems/sidekiq-benchmark-0.4.1/lib/sidekiq-benchmark.rb:4:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
~/Code/my_service/config/application.rb:8:in `<top (required)>'
~/Code/my_service/Rakefile:4:in `require'
~/Code/my_service/Rakefile:4:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/application.rb:79:in `block in run'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@my_service/bin/rake:23:in `load'
~/.rvm/gems/ruby-2.2.4@my_service/bin/rake:23:in `<main>'
~/.rvm/gems/ruby-2.2.4@my_service/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.2.4@my_service/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
~/Code/my_service/config/application.rb:8:in `<top (required)>'
~/Code/my_service/Rakefile:4:in `require'
~/Code/my_service/Rakefile:4:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@my_service/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.2.4@my_service/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `register' for Sidekiq::WebApplication:Class
~/.rvm/gems/ruby-2.2.4@my_service/gems/sidekiq-benchmark-0.4.1/lib/sidekiq-benchmark/web.rb:12:in `registered'
~/.rvm/gems/ruby-2.2.4@my_service/gems/sidekiq-4.2.2/lib/sidekiq/web.rb:101:in `register'
~/.rvm/gems/ruby-2.2.4@my_service/gems/sidekiq-benchmark-0.4.1/lib/sidekiq-benchmark.rb:4:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
~/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
~/Code/my_service/config/application.rb:8:in `<top (required)>'
~/Code/my_service/Rakefile:4:in `require'
~/Code/my_service/Rakefile:4:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@my_service/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@my_service/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.2.4@my_service/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kosmatov** [comment]
Fixed

**Comment by baburdick** [comment]
👍 +1 @kosmatov! Thank you, sir.

**Comment by baburdick** [comment]
One issue with this release: the sidekiq dependency should be adjusted: v0.5.0+ actually requires sidekiq v4.2+, now. Updating to v0.5.0 with sidekiq < v4.2 causes specs to fail looking for sinatra.

**Comment by kosmatov** [comment]
Ok, thanks
